export const siteConfig = {
  name: 'UTTsolar',
  legalName: 'UTTsolar',
  tagline: 'Premium Solar Solutions for Uttarakhand',
  description:
    'Residential, commercial and industrial solar installation across Uttarakhand. PM Surya Ghar subsidy assistance, net metering support and free site surveys.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://uttsolar.in',
  phone: '+918475014008',
  phoneDisplay: '+91 84750 14008',
  phoneSecondary: '+917830060725',
  phoneSecondaryDisplay: '+91 78300 60725',
  whatsapp: '918475014008',
  whatsappDisplay: '+91 84750 14008',
  whatsappSecondary: '917830060725',
  whatsappSecondaryDisplay: '+91 78300 60725',
  email: 'info@uttsolar.in',
  headOffice: {
    title: 'Head Office',
    street: 'Jawahar Jyoti, Damuadhunga',
    city: 'Haldwani',
    state: 'Uttarakhand',
    pincode: '263139',
    country: 'IN',
    fullAddress: 'Jawahar Jyoti, Damuadhunga, Haldwani, Uttarakhand (263139)',
  },
  corporateOffice: {
    title: 'Corporate Office',
    street: 'West rajeeva nagar, bindukhatta',
    city: 'Lalkuwan',
    state: 'Uttarakhand',
    pincode: '263145',
    country: 'IN',
    fullAddress: 'West rajeeva nagar, bindukhatta, Lalkuwan, Uttarakhand',
  },
  address: {
    street: 'Jawahar Jyoti, Damuadhunga',
    city: 'Haldwani',
    state: 'Uttarakhand',
    pincode: '263139',
    country: 'IN',
    fullAddress: 'Jawahar Jyoti, Damuadhunga, Haldwani, Uttarakhand (263139)',
  },
  social: {
    facebook: 'https://facebook.com/uttsolar',
    instagram: 'https://instagram.com/uttsolar',
    googleBusiness: 'https://maps.app.goo.gl/uYdkXurbkMtY64V2A',
    youtube: '',
  },
  businessHours: 'Mon–Sat: 9:00 AM – 7:00 PM',
  discom: 'UPCL (Uttarakhand Power Corporation Limited)',
  discomPortal: 'https://usrp.upcl.org/',
  pmSuryaGharPortal: 'https://pmsuryaghar.gov.in',
  locales: ['en', 'hi'] as const,
  defaultLocale: 'en' as const,
};

export type Locale = (typeof siteConfig.locales)[number];

