import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { siteConfig } from '@/config/site';
import { getAllServices } from '@/data/services';
import { districts } from '@/data/locations/districts';
import { getAllLocations } from '@/data/locations/locations';
import { getAllBlogs } from '@/data/blogs';
import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { SolarCalculator } from '@/components/calculator/SolarCalculator';
import { ContactForm } from '@/components/forms/ContactForm';
import { KeywordPillCycle } from '@/components/ui/KeywordPillCycle';
import {
  SunIcon,
  CheckCircleIcon,
  MapPinIcon,
  PhoneIcon,
  WhatsAppIcon,
  ArrowUpRightIcon,
  AwardIcon,
} from '@/components/ui/Icons';
import {
  localBusinessSchema,
  faqSchema,
  breadcrumbSchema,
  serviceSchema,
} from '@/lib/schema';

export const metadata: Metadata = {
  title: 'Solar Company in Uttarakhand | Best Rooftop Solar, Subsidy & Installation | UTTsolar',
  description:
    'Looking for the best solar company in Uttarakhand? UTTsolar is an authorized regional solar EPC provider offering residential, commercial & industrial rooftop solar, PM Surya Ghar subsidy up to ₹85,800 & UPCL net metering across all 13 districts.',
  alternates: {
    canonical: `${siteConfig.url}/locations/solar-company-in-uttarakhand/`,
  },
  openGraph: {
    title: 'Solar Company in Uttarakhand | Best Rooftop Solar & Subsidy | UTTsolar',
    description:
      'Authorized solar installation company in Uttarakhand. Avail PM Surya Ghar subsidy up to ₹85,800, UPCL net metering, Tier-1 solar panels, and turnkey EPC across Dehradun, Haldwani, Haridwar & all 13 districts.',
    url: `${siteConfig.url}/locations/solar-company-in-uttarakhand/`,
  },
};

const uttarakhandFaqs = [
  {
    question: 'Why is UTTsolar considered the best solar company in Uttarakhand?',
    answer:
      'UTTsolar is a dedicated regional solar engineering and EPC company with active installation and support operations across all 13 districts of Uttarakhand. We deliver Tier-1 Mono PERC & TOPCon solar panels with 25–30 year performance warranties, 150 km/h wind-rated mounting structures, end-to-end PM Surya Ghar subsidy documentation, and direct UPCL net meter synchronization with zero hassle.',
  },
  {
    question: 'How much subsidy is available for rooftop solar in Uttarakhand under PM Surya Ghar?',
    answer:
      'Uttarakhand qualifies as a Special Category State with enhanced Central Financial Assistance: ₹33,000 for 1 kW, ₹66,000 for 2 kW, and a maximum subsidy of ₹85,800 for 3 kW or larger residential rooftop solar plants. The subsidy is transferred directly to your bank account (DBT) upon UPCL net meter installation.',
  },
  {
    question: 'How does UPCL net metering work across Uttarakhand districts?',
    answer:
      'Under the UPCL net metering framework, solar power generated by your rooftop plant powers your property first. Any excess daytime electricity is exported to the grid. In the evening, you draw power from the grid. At month-end, UPCL bills you only for the net units consumed, with surplus exported units rolling forward across the billing year.',
  },
  {
    question: 'Can solar panels be installed on mountain sloping roofs and hill terrains?',
    answer:
      'Yes. We specialize in custom-engineered mounting structures for flat RCC terraces in plains (Haldwani, Haridwar, Dehradun, Rudrapur) as well as sloped tin/sheet and tile roofs in hill stations (Mussoorie, Nainital, Almora, Ranikhet, Pauri, Uttarkashi) using corrosion-proof aluminium and hot-dip galvanized steel.',
  },
  {
    question: 'What is the total cost and payback period for a 3 kW home solar plant in Uttarakhand?',
    answer:
      'A standard 3 kW residential rooftop solar plant costs approximately ₹1,65,000 to ₹1,95,000 before subsidy depending on structure height and inverter type. With the ₹85,800 PM Surya Ghar subsidy, the effective customer cost drops to approximately ₹80,000 to ₹1,10,000. With monthly bill savings of ₹2,500 to ₹3,500, full financial payback is achieved within 3 to 4 years.',
  },
  {
    question: 'Does UTTsolar provide commercial and industrial solar installations in Uttarakhand?',
    answer:
      'Yes. We design and commission commercial and industrial (C&I) solar plants from 10 kW to 1 MW+ for hotels, resorts, private hospitals, schools, and factories across SIDCUL Haridwar, Pantnagar, Kashipur, Roorkee, and Kotdwar. Commercial clients benefit from 40% accelerated depreciation and substantial reduction in peak daytime UPCL tariffs.',
  },
  {
    question: 'Will rooftop solar work during power cuts in Uttarakhand?',
    answer:
      'Standard on-grid solar systems shut down during grid outages for electrical line safety (anti-islanding). For customers requiring 24/7 power backup during outages, UTTsolar installs intelligent Hybrid Solar Systems equipped with Lithium (LiFePO4) battery storage for seamless, automatic switchover in milliseconds.',
  },
  {
    question: 'How can I book a free solar site survey with UTTsolar anywhere in Uttarakhand?',
    answer:
      'You can schedule a free on-site roof inspection by submitting our online booking form, calling +91 78300 60725, or reaching out via WhatsApp. Our local engineering team will visit your property, assess roof orientation and shading, review your UPCL bill, and deliver a detailed subsidy quotation.',
  },
];

export default function SolarCompanyInUttarakhandPage() {
  const services = getAllServices();
  const allLocations = getAllLocations();
  const blogs = getAllBlogs().slice(0, 3);

  const breadcrumbs = [
    { name: 'Locations', url: '/locations/' },
    { name: 'Solar Company in Uttarakhand', url: '/locations/solar-company-in-uttarakhand/' },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-10 space-y-12 sm:space-y-16">
      {/* Schemas */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            localBusinessSchema({
              name: 'UTTsolar - Best Solar Company in Uttarakhand',
              areaServed: 'Uttarakhand, India (All 13 Districts)',
            })
          ),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            serviceSchema(
              'Solar Panel Installation & Subsidy Services in Uttarakhand',
              'Turnkey residential, commercial and industrial rooftop solar installation with PM Surya Ghar subsidy and UPCL net metering across Uttarakhand.',
              '/locations/solar-company-in-uttarakhand/'
            )
          ),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(faqSchema(uttarakhandFaqs)),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(breadcrumbSchema(breadcrumbs)),
        }}
      />

      <Breadcrumbs items={breadcrumbs} />

      {/* Flagship Hero Header */}
      <section className="bg-[#17220F] text-white rounded-2xl sm:rounded-3xl p-8 sm:p-14 shadow-xl relative overflow-hidden border border-[#46A304]/20">
        <div className="max-w-3xl space-y-5">
          <div className="flex flex-wrap items-center gap-2">
            <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#46A304]/20 text-xs font-bold text-[#70C92F] border border-[#46A304]/30">
              <AwardIcon className="w-4 h-4 text-[#46A304]" />
              #1 Solar EPC &amp; PM Surya Ghar Partner
            </span>
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#FFDE21]/15 text-[#FFDE21] text-xs font-bold border border-[#FFDE21]/30">
              <MapPinIcon className="w-3.5 h-3.5" />
              All 13 Uttarakhand Districts Covered
            </span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-heading font-extrabold tracking-tight text-white leading-tight">
            Solar Company in Uttarakhand
          </h1>

          <p className="text-sm sm:text-base text-slate-300 leading-relaxed">
            UTTsolar is Uttarakhand&apos;s leading turnkey solar engineering company. We deliver high-efficiency rooftop solar installations, direct Central Financial Assistance up to <strong>₹85,800</strong> under PM Surya Ghar, seamless UPCL bidirectional net metering, and Tier-1 solar systems engineered specifically for mountain and plains climates.
          </p>

          {/* Quick Metrics Bar */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
            <div className="bg-[#1F2E14] p-3 rounded-2xl border border-[#46A304]/30 text-center">
              <div className="text-xl font-bold text-[#FFDE21]">₹85,800</div>
              <div className="text-[11px] text-slate-300">Max Central Subsidy</div>
            </div>
            <div className="bg-[#1F2E14] p-3 rounded-2xl border border-[#46A304]/30 text-center">
              <div className="text-xl font-bold text-[#46A304]">80–95%</div>
              <div className="text-[11px] text-slate-300">UPCL Bill Reduction</div>
            </div>
            <div className="bg-[#1F2E14] p-3 rounded-2xl border border-[#46A304]/30 text-center">
              <div className="text-xl font-bold text-white">25–30 Yrs</div>
              <div className="text-[11px] text-slate-300">Panel Warranty</div>
            </div>
            <div className="bg-[#1F2E14] p-3 rounded-2xl border border-[#46A304]/30 text-center">
              <div className="text-xl font-bold text-[#70C92F]">99 Towns</div>
              <div className="text-[11px] text-slate-300">Active Service Hubs</div>
            </div>
          </div>

          <div className="flex flex-wrap gap-3 pt-3">
            <Link
              href="/contact/?intent=quote"
              className="px-6 py-3 rounded-full text-xs sm:text-sm font-semibold text-[#17220F] bg-[#FFDE21] hover:bg-[#46A304] hover:text-white shadow-md transition"
            >
              Book Free Site Survey in Uttarakhand
            </Link>
            <a
              href={`tel:${siteConfig.phone}`}
              className="px-6 py-3 rounded-full text-xs sm:text-sm font-semibold text-white bg-white/10 hover:bg-white/15 border border-white/20 transition flex items-center gap-1.5"
            >
              <PhoneIcon className="w-4 h-4 text-[#46A304]" />
              <span>Call Solar Expert</span>
            </a>
            <a
              href={`https://wa.me/${siteConfig.whatsapp}?text=Hi%2C%20I%20need%20solar%20installation%20in%20Uttarakhand`}
              target="_blank"
              rel="noopener noreferrer"
              className="px-6 py-3 rounded-full text-xs sm:text-sm font-semibold text-white bg-[#25D366] hover:bg-[#1EBE5D] transition flex items-center gap-1.5 shadow-md"
            >
              <WhatsAppIcon className="w-4 h-4 text-white" />
              <span>WhatsApp</span>
            </a>
          </div>
        </div>
      </section>

      {/* Interactive Keyword & Navigation Pills */}
      <KeywordPillCycle
        currentSlug="solar-company-in-uttarakhand"
        title="Uttarakhand Solar Directory &amp; Keyword Navigation"
        description="Jump directly to localized solar company pages in your city, browse turnkey solutions, or explore district-level service portals."
      />

      {/* Complete Services & Solutions Directory (All 17 Services) */}
      <section className="space-y-8">
        <div className="text-center max-w-3xl mx-auto space-y-2">
          <span className="text-xs font-semibold uppercase tracking-wider text-[#2D5A27] bg-[#EBF5E1] px-3 py-1 rounded-full border border-[#46A304]/30">
            End-to-End Solutions
          </span>
          <h2 className="text-2xl sm:text-4xl font-heading font-extrabold text-[#17220F]">
            Comprehensive Solar Services Across Uttarakhand
          </h2>
          <p className="text-xs sm:text-sm text-[#66705F]">
            From residential rooftop installations under PM Surya Ghar to megawatt-scale industrial solar plants, we deliver end-to-end EPC services across all 13 districts.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {services.map((srv) => (
            <div
              key={srv.slug}
              className="bg-white p-6 rounded-3xl border border-[#E2E7DE] shadow-xs hover:border-[#46A304] hover:shadow-md transition flex flex-col justify-between group"
            >
              <div>
                <div className="w-10 h-10 rounded-2xl bg-[#EBF5E1] text-[#46A304] flex items-center justify-center font-bold mb-4 group-hover:bg-[#46A304] group-hover:text-white transition">
                  <SunIcon className="w-5 h-5" />
                </div>
                <h3 className="text-lg font-bold text-[#17220F] group-hover:text-[#46A304] transition">
                  <Link href={`/services/${srv.slug}/`}>{srv.title}</Link>
                </h3>
                <p className="text-xs text-[#66705F] mt-2 line-clamp-3 leading-relaxed">
                  {srv.intro}
                </p>

                <div className="mt-4 pt-3 border-t border-[#E2E7DE] space-y-1.5">
                  <span className="text-[11px] font-bold text-[#17220F] block">
                    Key Features:
                  </span>
                  <ul className="text-[11px] text-[#66705F] space-y-1">
                    {srv.sections.benefits.slice(0, 2).map((b, idx) => (
                      <li key={idx} className="flex items-start gap-1.5">
                        <CheckCircleIcon className="w-3.5 h-3.5 text-[#46A304] flex-shrink-0 mt-0.5" />
                        <span>{b.title}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="pt-4 mt-4 border-t border-[#E2E7DE]">
                <Link
                  href={`/services/${srv.slug}/`}
                  className="text-xs font-bold text-[#46A304] hover:text-[#2D5A27] flex items-center justify-between"
                >
                  <span>Explore {srv.title} Details</span>
                  <ArrowUpRightIcon className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 13 Districts & 99 Locations Directory Archive */}
      <section className="bg-[#F7F9F5] p-8 sm:p-12 rounded-3xl border border-[#E2E7DE] space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <span className="text-xs font-semibold uppercase tracking-wider text-[#2D5A27] bg-[#EBF5E1] px-3 py-1 rounded-full border border-[#46A304]/30">
              Statewide Coverage
            </span>
            <h2 className="text-2xl sm:text-3xl font-heading font-extrabold text-[#17220F] mt-2">
              All 13 Uttarakhand Districts &amp; 99 City Hubs
            </h2>
            <p className="text-xs sm:text-sm text-[#66705F] mt-1">
              Select your district to view localized solar feasibility, UPCL net metering rules, and active city landing pages.
            </p>
          </div>
          <Link
            href="/locations/"
            className="px-5 py-2.5 rounded-full text-xs font-bold bg-[#17220F] text-white hover:bg-[#46A304] transition whitespace-nowrap self-start sm:self-auto"
          >
            View Full Location Directory →
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {districts.map((d) => {
            const districtLocs = allLocations.filter((l) => l.districtSlug === d.slug);
            return (
              <div
                key={d.slug}
                className="bg-white p-6 rounded-2xl border border-[#E2E7DE] shadow-xs flex flex-col justify-between hover:border-[#46A304] transition"
              >
                <div>
                  <div className="flex items-center justify-between">
                    <span className="text-[11px] font-bold text-[#46A304] uppercase tracking-wider">
                      {districtLocs.length} City Hubs
                    </span>
                    <MapPinIcon className="w-4 h-4 text-[#46A304]" />
                  </div>
                  <h3 className="text-lg font-bold text-[#17220F] mt-1">
                    <Link href={`/locations/${d.slug}/`} className="hover:text-[#46A304] transition">
                      {d.name} District
                    </Link>
                  </h3>
                  <p className="text-xs text-[#66705F] mt-2 line-clamp-2 leading-relaxed">
                    {d.intro}
                  </p>

                  <div className="mt-3 pt-3 border-t border-[#E2E7DE]">
                    <span className="text-[11px] font-bold text-[#17220F] block mb-1.5">
                      Target Towns &amp; Cities:
                    </span>
                    <div className="flex flex-wrap gap-1.5">
                      {districtLocs.map((loc) => (
                        <Link
                          key={loc.slug}
                          href={`/locations/${d.slug}/${loc.slug}/`}
                          className="px-2 py-0.5 bg-[#F7F9F5] border border-[#E2E7DE] hover:border-[#46A304] hover:bg-[#EBF5E1] rounded-md text-[10px] font-semibold text-[#17220F] transition"
                        >
                          {loc.name}
                        </Link>
                      ))}
                    </div>
                  </div>
                </div>

                <div className="pt-4 mt-4 border-t border-[#E2E7DE]">
                  <Link
                    href={`/locations/${d.slug}/`}
                    className="text-xs font-bold text-[#46A304] hover:underline flex items-center justify-between"
                  >
                    <span>Explore {d.name} Solar Center</span>
                    <span>→</span>
                  </Link>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* PM Surya Ghar Subsidy Breakdown Table */}
      <section className="bg-white p-6 sm:p-10 rounded-3xl border border-[#E2E7DE] shadow-xs space-y-6">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <span className="text-xs font-semibold uppercase tracking-wider text-[#2D5A27] bg-[#EBF5E1] px-3 py-1 rounded-full border border-[#46A304]/30">
            Government Financial Support
          </span>
          <h2 className="text-2xl sm:text-3xl font-heading font-extrabold text-[#17220F]">
            PM Surya Ghar: Muft Bijli Yojana in Uttarakhand
          </h2>
          <p className="text-xs sm:text-sm text-[#66705F]">
            Uttarakhand qualifies for Special Category State Central Financial Assistance (CFA). Subsidies are credited directly to your bank account via DBT.
          </p>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs sm:text-sm">
            <thead>
              <tr className="bg-[#17220F] text-white">
                <th className="p-3.5 font-bold rounded-tl-xl">System Capacity</th>
                <th className="p-3.5 font-bold">Daily Generation</th>
                <th className="p-3.5 font-bold">Monthly Savings</th>
                <th className="p-3.5 font-bold">Govt. Subsidy (CFA)</th>
                <th className="p-3.5 font-bold rounded-tr-xl">Net Effective Cost</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#E2E7DE] bg-[#F7F9F5]">
              <tr>
                <td className="p-3.5 font-bold text-[#17220F]">1 kW System</td>
                <td className="p-3.5 text-[#66705F]">4–5 Units</td>
                <td className="p-3.5 text-[#66705F]">₹800–₹1,200</td>
                <td className="p-3.5 font-bold text-[#46A304]">₹33,000</td>
                <td className="p-3.5 font-bold text-[#17220F]">₹35,000–₹45,000</td>
              </tr>
              <tr className="bg-white">
                <td className="p-3.5 font-bold text-[#17220F]">2 kW System</td>
                <td className="p-3.5 text-[#66705F]">8–10 Units</td>
                <td className="p-3.5 text-[#66705F]">₹1,800–₹2,400</td>
                <td className="p-3.5 font-bold text-[#46A304]">₹66,000</td>
                <td className="p-3.5 font-bold text-[#17220F]">₹55,000–₹65,000</td>
              </tr>
              <tr className="bg-[#EBF5E1]/50">
                <td className="p-3.5 font-bold text-[#17220F]">3 kW System (Most Popular)</td>
                <td className="p-3.5 text-[#66705F]">12–15 Units</td>
                <td className="p-3.5 text-[#66705F]">₹2,800–₹3,800</td>
                <td className="p-3.5 font-bold text-[#46A304]">₹85,800 (Maximum)</td>
                <td className="p-3.5 font-bold text-[#2D5A27]">₹80,000–₹1,10,000</td>
              </tr>
              <tr className="bg-white">
                <td className="p-3.5 font-bold text-[#17220F]">5 kW to 10 kW System</td>
                <td className="p-3.5 text-[#66705F]">20–45 Units</td>
                <td className="p-3.5 text-[#66705F]">₹5,000–₹12,000+</td>
                <td className="p-3.5 font-bold text-[#46A304]">₹85,800</td>
                <td className="p-3.5 font-bold text-[#17220F]">Based on exact capacity</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* Embedded Calculator */}
      <section className="space-y-6">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <span className="text-xs font-semibold uppercase tracking-wider text-[#2D5A27] bg-[#EBF5E1] px-3 py-1 rounded-full border border-[#46A304]/30">
            Instant Estimate
          </span>
          <h2 className="text-2xl sm:text-3xl font-heading font-extrabold text-[#17220F]">
            Calculate Your Solar ROI in Uttarakhand
          </h2>
          <p className="text-xs sm:text-sm text-[#66705F]">
            Select your district and enter your monthly UPCL electricity bill to calculate recommended kW size, subsidies, and 25-year savings.
          </p>
        </div>
        <SolarCalculator initialDistrict="dehradun" />
      </section>

      {/* In-Depth Localized FAQs */}
      <section className="max-w-4xl mx-auto space-y-6">
        <div className="text-center space-y-2">
          <span className="text-xs font-semibold uppercase tracking-wider text-[#2D5A27] bg-[#EBF5E1] px-3 py-1 rounded-full border border-[#46A304]/30">
            Got Questions?
          </span>
          <h2 className="text-2xl sm:text-3xl font-heading font-extrabold text-[#17220F]">
            Frequently Asked Questions — Solar in Uttarakhand
          </h2>
        </div>

        <div className="space-y-3">
          {uttarakhandFaqs.map((faq, idx) => (
            <details
              key={idx}
              className="bg-white p-5 rounded-2xl border border-[#E2E7DE] shadow-xs group [&_summary::-webkit-details-marker]:hidden"
            >
              <summary className="flex items-center justify-between cursor-pointer text-sm font-bold text-[#17220F] group-open:text-[#46A304] transition">
                <span>{faq.question}</span>
                <span className="w-6 h-6 rounded-full bg-[#F7F9F5] flex items-center justify-center text-xs font-bold text-[#66705F] group-open:rotate-180 transition">
                  ▼
                </span>
              </summary>
              <p className="text-xs sm:text-sm text-[#66705F] leading-relaxed mt-3 pt-3 border-t border-[#E2E7DE]">
                {faq.answer}
              </p>
            </details>
          ))}
        </div>
      </section>

      {/* Related Blog Guides */}
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-xl font-bold text-[#17220F]">
            Latest Uttarakhand Solar Guides &amp; Insights
          </h3>
          <Link href="/blog/" className="text-xs font-semibold text-[#46A304] hover:underline">
            View All Articles →
          </Link>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {blogs.map((b) => (
            <Link
              key={b.slug}
              href={`/blog/${b.slug}/`}
              className="p-5 rounded-2xl bg-white border border-[#E2E7DE] hover:border-[#46A304] hover:shadow-xs transition group flex flex-col justify-between"
            >
              <div>
                <span className="text-[10px] font-semibold text-[#46A304] uppercase tracking-wider block mb-1">
                  {b.category}
                </span>
                <h4 className="text-sm font-bold text-[#17220F] group-hover:text-[#46A304] transition line-clamp-2">
                  {b.title}
                </h4>
                <p className="text-xs text-[#66705F] mt-2 line-clamp-2">
                  {b.excerpt}
                </p>
              </div>
              <span className="text-[11px] font-semibold text-[#46A304] mt-3 block">
                Read guide →
              </span>
            </Link>
          ))}
        </div>
      </section>

      {/* Lead Capture Form */}
      <section className="bg-[#F7F9F5] rounded-2xl sm:rounded-3xl p-6 sm:p-10 border border-[#E2E7DE]">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
          <div className="lg:col-span-6 space-y-4">
            <span className="text-xs font-semibold uppercase tracking-wider text-[#2D5A27] bg-[#EBF5E1] px-3 py-1 rounded-full border border-[#46A304]/30">
              Free Site Survey
            </span>
            <h2 className="text-2xl sm:text-3xl font-heading font-extrabold text-[#17220F]">
              Book Your Solar Consultation in Uttarakhand
            </h2>
            <p className="text-xs sm:text-sm text-[#66705F] leading-relaxed">
              Our regional solar engineering team will visit your property anywhere in Uttarakhand, calculate your exact roof shading, and deliver a comprehensive PM Surya Ghar subsidy estimate.
            </p>
            <div className="space-y-2 pt-2 text-xs text-[#17220F]">
              <div className="flex items-center gap-2">
                <CheckCircleIcon className="w-4 h-4 text-[#46A304]" />
                <span>100% Free On-Site Roof Assessment</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircleIcon className="w-4 h-4 text-[#46A304]" />
                <span>Tier-1 Panels with 25-Year Performance Warranty</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircleIcon className="w-4 h-4 text-[#46A304]" />
                <span>End-to-End UPCL Net Metering &amp; DBT Subsidy Support</span>
              </div>
            </div>
          </div>
          <div className="lg:col-span-6">
            <ContactForm defaultDistrict="dehradun" />
          </div>
        </div>
      </section>
    </div>
  );
}
